# Generated by Django 3.1.1 on 2020-09-27 19:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient')),
            ],
        ),
    ]
