# Generated by Django 3.1.1 on 2020-09-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientproperty_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientproperty',
            name='order',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
