# Generated by Django 3.1.1 on 2020-09-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientstoryexcerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientproperty',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientstoryexcerpt',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
