# Generated by Django 3.1.1 on 2020-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20200929_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
