# Generated by Django 3.1.1 on 2020-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20201003_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
