# Generated by Django 3.1.1 on 2020-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstory',
            name='excerpt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='PatientStoryExcerpt',
        ),
    ]
