# Generated by Django 3.1.1 on 2020-10-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('patients', '0010_auto_20201006_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='patientstory',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
