# Generated by Django 3.1.1 on 2020-11-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('patients', '0011_auto_20201006_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstory',
            name='excerpt',
        ),
        migrations.CreateModel(
            name='PatientStoryHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
