# Generated by Django 3.1.1 on 2020-11-01 21:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('patients', '0012_auto_20201101_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=250)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.attribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='patientproperty',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientproperty',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='patientstory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientstory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='patientstoryhighlight',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientstoryhighlight',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='PatientProperty',
        ),
        migrations.AddField(
            model_name='patientattribute',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient'),
        ),
    ]
