# Generated by Django 3.1.1 on 2020-11-24 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20201120_1722'),
        ('patients', '0015_issue_posttransplantissue_pretransplantissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resources.resource'),
        ),
    ]
