# Generated by Django 3.1.1 on 2020-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_attribute_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='patientstory',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='patientstoryhighlight',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='patientstory',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientstoryhighlight',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
