# Generated by Django 3.1.1 on 2021-01-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20201206_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='warning',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
