# Generated by Django 3.1.1 on 2021-02-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20210124_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='warning',
        ),
    ]
