# Generated by Django 3.1.1 on 2021-02-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_agency_version', models.BooleanField()),
                ('integrated_content_version', models.BooleanField()),
                ('start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
