# Generated by Django 3.1.1 on 2021-02-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='persona',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
