# Generated by Django 3.1.1 on 2021-02-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_studysession_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
