# Generated by Django 3.1.1 on 2021-02-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20210223_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'order', 'name']},
        ),
    ]
