# Generated by Django 3.1.1 on 2020-10-06 21:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('published', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
