# Generated by Django 3.1.1 on 2020-10-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201006_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
