# Generated by Django 3.1.1 on 2020-11-12 01:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.CharField(max_length=70, null=True)),
                ('published', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
