# Generated by Django 3.1.1 on 2020-11-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='content',
        ),
    ]
