# Generated by Django 3.1.1 on 2021-02-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.article'),
        ),
    ]
