# Generated by Django 3.1.1 on 2021-02-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedcontent',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='study_sessions.studysession'),
        ),
    ]
