# Generated by Django 3.1.1 on 2021-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_highlightedcontent_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
