# Generated by Django 3.1.1 on 2021-01-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20210124_2225'),
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient'),
        ),
    ]
