# Generated by Django 3.1.1 on 2021-02-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_auto_20210216_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='patient',
        ),
    ]
