# Generated by Django 3.1.1 on 2021-02-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_remove_answer_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='faqs.frequentlyaskedquestion')),
            ],
        ),
    ]
